// @generated by scripts/generate_token_kind.py; do not edit.
// To regenerate, run: python scripts/generate_token_kind.py

#![allow(unused)]

#[derive(Clone, Copy, Debug)]
pub enum DirectiveNode<'tree> {
    Include(IncludeNode<'tree>),
    Option(OptionNode<'tree>),
    Plugin(PluginNode<'tree>),
    Popmeta(PopmetaNode<'tree>),
    Poptag(PoptagNode<'tree>),
    Pushmeta(PushmetaNode<'tree>),
    Pushtag(PushtagNode<'tree>),
}

impl<'tree> DirectiveNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        match node.kind() {
            "include" => Some(DirectiveNode::Include(IncludeNode(node))),
            "option" => Some(DirectiveNode::Option(OptionNode(node))),
            "plugin" => Some(DirectiveNode::Plugin(PluginNode(node))),
            "popmeta" => Some(DirectiveNode::Popmeta(PopmetaNode(node))),
            "poptag" => Some(DirectiveNode::Poptag(PoptagNode(node))),
            "pushmeta" => Some(DirectiveNode::Pushmeta(PushmetaNode(node))),
            "pushtag" => Some(DirectiveNode::Pushtag(PushtagNode(node))),
            _ => None,
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        match self {
            DirectiveNode::Include(n) => n.0,
            DirectiveNode::Option(n) => n.0,
            DirectiveNode::Plugin(n) => n.0,
            DirectiveNode::Popmeta(n) => n.0,
            DirectiveNode::Poptag(n) => n.0,
            DirectiveNode::Pushmeta(n) => n.0,
            DirectiveNode::Pushtag(n) => n.0,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub enum EntryNode<'tree> {
    Balance(BalanceNode<'tree>),
    Close(CloseNode<'tree>),
    Commodity(CommodityNode<'tree>),
    Custom(CustomNode<'tree>),
    Document(DocumentNode<'tree>),
    Event(EventNode<'tree>),
    Note(NoteNode<'tree>),
    Open(OpenNode<'tree>),
    Pad(PadNode<'tree>),
    Price(PriceNode<'tree>),
    Query(QueryNode<'tree>),
    Transaction(TransactionNode<'tree>),
}

impl<'tree> EntryNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        match node.kind() {
            "balance" => Some(EntryNode::Balance(BalanceNode(node))),
            "close" => Some(EntryNode::Close(CloseNode(node))),
            "commodity" => Some(EntryNode::Commodity(CommodityNode(node))),
            "custom" => Some(EntryNode::Custom(CustomNode(node))),
            "document" => Some(EntryNode::Document(DocumentNode(node))),
            "event" => Some(EntryNode::Event(EventNode(node))),
            "note" => Some(EntryNode::Note(NoteNode(node))),
            "open" => Some(EntryNode::Open(OpenNode(node))),
            "pad" => Some(EntryNode::Pad(PadNode(node))),
            "price" => Some(EntryNode::Price(PriceNode(node))),
            "query" => Some(EntryNode::Query(QueryNode(node))),
            "transaction" => Some(EntryNode::Transaction(TransactionNode(node))),
            _ => None,
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        match self {
            EntryNode::Balance(n) => n.0,
            EntryNode::Close(n) => n.0,
            EntryNode::Commodity(n) => n.0,
            EntryNode::Custom(n) => n.0,
            EntryNode::Document(n) => n.0,
            EntryNode::Event(n) => n.0,
            EntryNode::Note(n) => n.0,
            EntryNode::Open(n) => n.0,
            EntryNode::Pad(n) => n.0,
            EntryNode::Price(n) => n.0,
            EntryNode::Query(n) => n.0,
            EntryNode::Transaction(n) => n.0,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct AmountNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> AmountNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "amount" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn binary_number_exprs(&self) -> Vec<BinaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BinaryNumberExprNode::cast)
            .collect()
    }
    pub fn currencies(&self) -> Vec<CurrencyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CurrencyNode::cast)
            .collect()
    }
    pub fn numbers(&self) -> Vec<NumberNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(NumberNode::cast)
            .collect()
    }
    pub fn unary_number_exprs(&self) -> Vec<UnaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnaryNumberExprNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct AmountToleranceNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> AmountToleranceNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "amount_tolerance" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn binary_number_exprs(&self) -> Vec<BinaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BinaryNumberExprNode::cast)
            .collect()
    }
    pub fn currencies(&self) -> Vec<CurrencyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CurrencyNode::cast)
            .collect()
    }
    pub fn numbers(&self) -> Vec<NumberNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(NumberNode::cast)
            .collect()
    }
    pub fn unary_number_exprs(&self) -> Vec<UnaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnaryNumberExprNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct AsteriskNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> AsteriskNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "asterisk" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct BalanceNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> BalanceNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "balance" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("account")
            .and_then(AccountNode::cast)
    }
    pub fn amount(&self) -> Option<AmountToleranceNode<'tree>> {
        self.0
            .child_by_field_name("amount")
            .and_then(AmountToleranceNode::cast)
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct BinaryNumberExprNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> BinaryNumberExprNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "binary_number_expr" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn asterisks(&self) -> Vec<AsteriskNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(AsteriskNode::cast)
            .collect()
    }
    pub fn binary_number_exprs(&self) -> Vec<BinaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BinaryNumberExprNode::cast)
            .collect()
    }
    pub fn minus_list(&self) -> Vec<MinusNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(MinusNode::cast)
            .collect()
    }
    pub fn numbers(&self) -> Vec<NumberNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(NumberNode::cast)
            .collect()
    }
    pub fn plus_list(&self) -> Vec<PlusNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(PlusNode::cast)
            .collect()
    }
    pub fn slashs(&self) -> Vec<SlashNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(SlashNode::cast)
            .collect()
    }
    pub fn unary_number_exprs(&self) -> Vec<UnaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnaryNumberExprNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CloseNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CloseNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "close" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("account")
            .and_then(AccountNode::cast)
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CommodityNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CommodityNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "commodity" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn currency(&self) -> Option<CurrencyNode<'tree>> {
        self.0
            .child_by_field_name("currency")
            .and_then(CurrencyNode::cast)
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CompoundAmountNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CompoundAmountNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "compound_amount" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn currency(&self) -> Option<CurrencyNode<'tree>> {
        self.0
            .child_by_field_name("currency")
            .and_then(CurrencyNode::cast)
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CostCompNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CostCompNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "cost_comp" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn compound_amounts(&self) -> Vec<CompoundAmountNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CompoundAmountNode::cast)
            .collect()
    }
    pub fn dates(&self) -> Vec<DateNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(DateNode::cast)
            .collect()
    }
    pub fn strings(&self) -> Vec<StringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(StringNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CostSpecNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CostSpecNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "cost_spec" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn cost_comp_list(&self) -> Vec<CostCompNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("cost_comp_list", &mut cursor)
            .filter_map(CostCompNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CustomNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CustomNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "custom" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn custom_value_list(&self) -> Vec<CustomValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("custom_value_list", &mut cursor)
            .filter_map(CustomValueNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn name(&self) -> Option<StringNode<'tree>> {
        self.0
            .child_by_field_name("name")
            .and_then(StringNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CustomValueNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CustomValueNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "custom_value" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn accounts(&self) -> Vec<AccountNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(AccountNode::cast)
            .collect()
    }
    pub fn amounts(&self) -> Vec<AmountNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(AmountNode::cast)
            .collect()
    }
    pub fn binary_number_exprs(&self) -> Vec<BinaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BinaryNumberExprNode::cast)
            .collect()
    }
    pub fn bools(&self) -> Vec<BoolNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BoolNode::cast)
            .collect()
    }
    pub fn dates(&self) -> Vec<DateNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(DateNode::cast)
            .collect()
    }
    pub fn numbers(&self) -> Vec<NumberNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(NumberNode::cast)
            .collect()
    }
    pub fn strings(&self) -> Vec<StringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(StringNode::cast)
            .collect()
    }
    pub fn unary_number_exprs(&self) -> Vec<UnaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnaryNumberExprNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct DocumentNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> DocumentNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "document" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("account")
            .and_then(AccountNode::cast)
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn filename(&self) -> Option<FilenameNode<'tree>> {
        self.0
            .child_by_field_name("filename")
            .and_then(FilenameNode::cast)
    }
    pub fn tags_links(&self) -> Option<TagsLinksNode<'tree>> {
        self.0
            .child_by_field_name("tags_links")
            .and_then(TagsLinksNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct EventNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> EventNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "event" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn desc(&self) -> Option<StringNode<'tree>> {
        self.0
            .child_by_field_name("desc")
            .and_then(StringNode::cast)
    }
    pub fn type_(&self) -> Option<StringNode<'tree>> {
        self.0
            .child_by_field_name("type")
            .and_then(StringNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct FileNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> FileNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "file" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn directives(&self) -> Vec<DirectiveNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(DirectiveNode::cast)
            .collect()
    }
    pub fn entries(&self) -> Vec<EntryNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(EntryNode::cast)
            .collect()
    }
    pub fn comments(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn flags(&self) -> Vec<FlagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(FlagNode::cast)
            .collect()
    }
    pub fn sections(&self) -> Vec<SectionNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(SectionNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct FilenameNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> FilenameNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "filename" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn strings(&self) -> Vec<StringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(StringNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct HeadlineNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> HeadlineNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "headline" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn item(&self) -> Option<ItemNode<'tree>> {
        self.0.child_by_field_name("item").and_then(ItemNode::cast)
    }
}

#[derive(Clone, Copy, Debug)]
pub struct IncludeNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> IncludeNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "include" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn strings(&self) -> Vec<StringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(StringNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct IncompleteAmountNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> IncompleteAmountNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "incomplete_amount" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn binary_number_exprs(&self) -> Vec<BinaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BinaryNumberExprNode::cast)
            .collect()
    }
    pub fn currencies(&self) -> Vec<CurrencyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CurrencyNode::cast)
            .collect()
    }
    pub fn numbers(&self) -> Vec<NumberNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(NumberNode::cast)
            .collect()
    }
    pub fn unary_number_exprs(&self) -> Vec<UnaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnaryNumberExprNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct KeyValueNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> KeyValueNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "key_value" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn value(&self) -> Option<ValueNode<'tree>> {
        self.0
            .child_by_field_name("value")
            .and_then(ValueNode::cast)
    }
    pub fn keys(&self) -> Vec<KeyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct NoteNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> NoteNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "note" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("account")
            .and_then(AccountNode::cast)
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn note(&self) -> Option<StringNode<'tree>> {
        self.0
            .child_by_field_name("note")
            .and_then(StringNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct OpenNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> OpenNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "open" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("account")
            .and_then(AccountNode::cast)
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn currencies(&self) -> Vec<CurrencyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("currencies", &mut cursor)
            .filter_map(CurrencyNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn opt_booking(&self) -> Option<OptBookingNode<'tree>> {
        self.0
            .child_by_field_name("opt_booking")
            .and_then(OptBookingNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct OptBookingNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> OptBookingNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "opt_booking" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn strings(&self) -> Vec<StringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(StringNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct OptflagNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> OptflagNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "optflag" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn flags(&self) -> Vec<FlagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(FlagNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct OptionNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> OptionNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "option" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn key(&self) -> Option<StringNode<'tree>> {
        self.0.child_by_field_name("key").and_then(StringNode::cast)
    }
    pub fn value(&self) -> Option<StringNode<'tree>> {
        self.0
            .child_by_field_name("value")
            .and_then(StringNode::cast)
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PadNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PadNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "pad" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("account")
            .and_then(AccountNode::cast)
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn from_account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("from_account")
            .and_then(AccountNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PluginNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PluginNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "plugin" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn strings(&self) -> Vec<StringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(StringNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PopmetaNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PopmetaNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "popmeta" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn keys(&self) -> Vec<KeyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PoptagNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PoptagNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "poptag" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn tags(&self) -> Vec<TagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(TagNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PostingNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PostingNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "posting" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn account(&self) -> Option<AccountNode<'tree>> {
        self.0
            .child_by_field_name("account")
            .and_then(AccountNode::cast)
    }
    pub fn amount(&self) -> Option<IncompleteAmountNode<'tree>> {
        self.0
            .child_by_field_name("amount")
            .and_then(IncompleteAmountNode::cast)
    }
    pub fn comment(&self) -> Option<CommentNode<'tree>> {
        self.0
            .child_by_field_name("comment")
            .and_then(CommentNode::cast)
    }
    pub fn cost_spec(&self) -> Option<CostSpecNode<'tree>> {
        self.0
            .child_by_field_name("cost_spec")
            .and_then(CostSpecNode::cast)
    }
    pub fn optflag(&self) -> Option<OptflagNode<'tree>> {
        self.0
            .child_by_field_name("optflag")
            .and_then(OptflagNode::cast)
    }
    pub fn price_annotation(&self) -> Option<PriceAnnotationNode<'tree>> {
        self.0
            .child_by_field_name("price_annotation")
            .and_then(PriceAnnotationNode::cast)
    }
    pub fn ats(&self) -> Vec<AtNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(AtNode::cast)
            .collect()
    }
    pub fn atats(&self) -> Vec<AtatNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(AtatNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PriceNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PriceNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "price" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn amount(&self) -> Option<AmountNode<'tree>> {
        self.0
            .child_by_field_name("amount")
            .and_then(AmountNode::cast)
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn currency(&self) -> Option<CurrencyNode<'tree>> {
        self.0
            .child_by_field_name("currency")
            .and_then(CurrencyNode::cast)
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PriceAnnotationNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PriceAnnotationNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "price_annotation" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn currencies(&self) -> Vec<CurrencyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CurrencyNode::cast)
            .collect()
    }
    pub fn incomplete_amounts(&self) -> Vec<IncompleteAmountNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(IncompleteAmountNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PushmetaNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PushmetaNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "pushmeta" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PushtagNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PushtagNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "pushtag" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn tags(&self) -> Vec<TagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(TagNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct QueryNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> QueryNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "query" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn name(&self) -> Option<StringNode<'tree>> {
        self.0
            .child_by_field_name("name")
            .and_then(StringNode::cast)
    }
    pub fn query(&self) -> Option<StringNode<'tree>> {
        self.0
            .child_by_field_name("query")
            .and_then(StringNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct SectionNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> SectionNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "section" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn headline(&self) -> Option<HeadlineNode<'tree>> {
        self.0
            .child_by_field_name("headline")
            .and_then(HeadlineNode::cast)
    }
    pub fn subsection(&self) -> Vec<SectionNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("subsection", &mut cursor)
            .filter_map(SectionNode::cast)
            .collect()
    }
    pub fn directives(&self) -> Vec<DirectiveNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(DirectiveNode::cast)
            .collect()
    }
    pub fn entries(&self) -> Vec<EntryNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(EntryNode::cast)
            .collect()
    }
    pub fn comments(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn flags(&self) -> Vec<FlagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(FlagNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct TagsLinksNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> TagsLinksNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "tags_links" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn links(&self) -> Vec<LinkNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(LinkNode::cast)
            .collect()
    }
    pub fn tags(&self) -> Vec<TagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(TagNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct TransactionNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> TransactionNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "transaction" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn comment(&self) -> Vec<CommentNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .children_by_field_name("comment", &mut cursor)
            .filter_map(CommentNode::cast)
            .collect()
    }
    pub fn date(&self) -> Option<DateNode<'tree>> {
        self.0.child_by_field_name("date").and_then(DateNode::cast)
    }
    pub fn narration(&self) -> Option<NarrationNode<'tree>> {
        self.0
            .child_by_field_name("narration")
            .and_then(NarrationNode::cast)
    }
    pub fn payee(&self) -> Option<PayeeNode<'tree>> {
        self.0
            .child_by_field_name("payee")
            .and_then(PayeeNode::cast)
    }
    pub fn tags_links(&self) -> Option<TagsLinksNode<'tree>> {
        self.0
            .child_by_field_name("tags_links")
            .and_then(TagsLinksNode::cast)
    }
    pub fn txn(&self) -> Option<TxnNode<'tree>> {
        self.0.child_by_field_name("txn").and_then(TxnNode::cast)
    }
    pub fn key_values(&self) -> Vec<KeyValueNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(KeyValueNode::cast)
            .collect()
    }
    pub fn postings(&self) -> Vec<PostingNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(PostingNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct TxnNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> TxnNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "txn" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn flags(&self) -> Vec<FlagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(FlagNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct UnaryNumberExprNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> UnaryNumberExprNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "unary_number_expr" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn binary_number_exprs(&self) -> Vec<BinaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BinaryNumberExprNode::cast)
            .collect()
    }
    pub fn minus_list(&self) -> Vec<MinusNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(MinusNode::cast)
            .collect()
    }
    pub fn numbers(&self) -> Vec<NumberNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(NumberNode::cast)
            .collect()
    }
    pub fn plus_list(&self) -> Vec<PlusNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(PlusNode::cast)
            .collect()
    }
    pub fn unary_number_exprs(&self) -> Vec<UnaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnaryNumberExprNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct ValueNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> ValueNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "value" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn accounts(&self) -> Vec<AccountNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(AccountNode::cast)
            .collect()
    }
    pub fn amounts(&self) -> Vec<AmountNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(AmountNode::cast)
            .collect()
    }
    pub fn binary_number_exprs(&self) -> Vec<BinaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BinaryNumberExprNode::cast)
            .collect()
    }
    pub fn bools(&self) -> Vec<BoolNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(BoolNode::cast)
            .collect()
    }
    pub fn currencies(&self) -> Vec<CurrencyNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(CurrencyNode::cast)
            .collect()
    }
    pub fn dates(&self) -> Vec<DateNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(DateNode::cast)
            .collect()
    }
    pub fn numbers(&self) -> Vec<NumberNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(NumberNode::cast)
            .collect()
    }
    pub fn strings(&self) -> Vec<StringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(StringNode::cast)
            .collect()
    }
    pub fn tags(&self) -> Vec<TagNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(TagNode::cast)
            .collect()
    }
    pub fn unary_number_exprs(&self) -> Vec<UnaryNumberExprNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnaryNumberExprNode::cast)
            .collect()
    }
    pub fn unquoted_strings(&self) -> Vec<UnquotedStringNode<'tree>> {
        let mut cursor = self.0.walk();
        self.0
            .named_children(&mut cursor)
            .filter_map(UnquotedStringNode::cast)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct AccountNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> AccountNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "account" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct AtNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> AtNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "at" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct AtatNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> AtatNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "atat" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct BoolNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> BoolNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "bool" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CommentNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CommentNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "comment" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CurrencyNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> CurrencyNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "currency" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct DateNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> DateNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "date" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct FlagNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> FlagNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "flag" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct ItemNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> ItemNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "item" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct KeyNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> KeyNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "key" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct LinkNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> LinkNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "link" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct MinusNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> MinusNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "minus" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct NarrationNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> NarrationNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "narration" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct NumberNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> NumberNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "number" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PayeeNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PayeeNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "payee" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct PlusNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> PlusNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "plus" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct SlashNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> SlashNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "slash" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct StringNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> StringNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "string" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct TagNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> TagNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "tag" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}

#[derive(Clone, Copy, Debug)]
pub struct UnquotedStringNode<'tree>(tree_sitter::Node<'tree>);

impl<'tree> UnquotedStringNode<'tree> {
    pub fn cast(node: tree_sitter::Node<'tree>) -> Option<Self> {
        if node.kind() == "unquoted_string" {
            Some(Self(node))
        } else {
            None
        }
    }
    pub fn node(&self) -> tree_sitter::Node<'tree> {
        self.0
    }
    pub fn text<'src>(&self, src: &'src [u8]) -> &'src str {
        self.0.utf8_text(src).unwrap_or("")
    }
}
