// @generated by scripts/generate_token_kind.py; do not edit.
// To regenerate, run: python scripts/generate_token_kind.py

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NodeKine {
    Account,
    Asterisk,
    At,
    Atat,
    Bool,
    Comment,
    Currency,
    Date,
    Flag,
    Item,
    Key,
    Link,
    Minus,
    Narration,
    Number,
    Payee,
    Plus,
    Slash,
    String,
    Tag,
    Unknown,
}

impl From<&str> for NodeKine {
    fn from(name: &str) -> Self {
        match name {
            "account" => NodeKine::Account,
            "asterisk" => NodeKine::Asterisk,
            "at" => NodeKine::At,
            "atat" => NodeKine::Atat,
            "bool" => NodeKine::Bool,
            "comment" => NodeKine::Comment,
            "currency" => NodeKine::Currency,
            "date" => NodeKine::Date,
            "flag" => NodeKine::Flag,
            "item" => NodeKine::Item,
            "key" => NodeKine::Key,
            "link" => NodeKine::Link,
            "minus" => NodeKine::Minus,
            "narration" => NodeKine::Narration,
            "number" => NodeKine::Number,
            "payee" => NodeKine::Payee,
            "plus" => NodeKine::Plus,
            "slash" => NodeKine::Slash,
            "string" => NodeKine::String,
            "tag" => NodeKine::Tag,
            _ => NodeKine::Unknown,
        }
    }
}

impl NodeKine {
    pub fn name(&self) -> &'static str {
        match self {
            NodeKine::Account => "account",
            NodeKine::Asterisk => "asterisk",
            NodeKine::At => "at",
            NodeKine::Atat => "atat",
            NodeKine::Bool => "bool",
            NodeKine::Comment => "comment",
            NodeKine::Currency => "currency",
            NodeKine::Date => "date",
            NodeKine::Flag => "flag",
            NodeKine::Item => "item",
            NodeKine::Key => "key",
            NodeKine::Link => "link",
            NodeKine::Minus => "minus",
            NodeKine::Narration => "narration",
            NodeKine::Number => "number",
            NodeKine::Payee => "payee",
            NodeKine::Plus => "plus",
            NodeKine::Slash => "slash",
            NodeKine::String => "string",
            NodeKine::Tag => "tag",
            NodeKine::Unknown => "<unknown>",
        }
    }
}

