// @generated by scripts/generate_token_kind.py; do not edit.
// To regenerate, run: python scripts/generate_token_kind.py

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NodeKind {
    Account,
    Asterisk,
    At,
    Atat,
    Bool,
    Comment,
    Currency,
    Date,
    Flag,
    Item,
    Key,
    Link,
    Minus,
    Narration,
    Number,
    Payee,
    Plus,
    Slash,
    String,
    Tag,
    Unknown,
}

impl From<&str> for NodeKind {
    fn from(name: &str) -> Self {
        match name {
            "account" => NodeKind::Account,
            "asterisk" => NodeKind::Asterisk,
            "at" => NodeKind::At,
            "atat" => NodeKind::Atat,
            "bool" => NodeKind::Bool,
            "comment" => NodeKind::Comment,
            "currency" => NodeKind::Currency,
            "date" => NodeKind::Date,
            "flag" => NodeKind::Flag,
            "item" => NodeKind::Item,
            "key" => NodeKind::Key,
            "link" => NodeKind::Link,
            "minus" => NodeKind::Minus,
            "narration" => NodeKind::Narration,
            "number" => NodeKind::Number,
            "payee" => NodeKind::Payee,
            "plus" => NodeKind::Plus,
            "slash" => NodeKind::Slash,
            "string" => NodeKind::String,
            "tag" => NodeKind::Tag,
            _ => NodeKind::Unknown,
        }
    }
}

impl NodeKind {
    pub fn name(&self) -> &'static str {
        match self {
            NodeKind::Account => "account",
            NodeKind::Asterisk => "asterisk",
            NodeKind::At => "at",
            NodeKind::Atat => "atat",
            NodeKind::Bool => "bool",
            NodeKind::Comment => "comment",
            NodeKind::Currency => "currency",
            NodeKind::Date => "date",
            NodeKind::Flag => "flag",
            NodeKind::Item => "item",
            NodeKind::Key => "key",
            NodeKind::Link => "link",
            NodeKind::Minus => "minus",
            NodeKind::Narration => "narration",
            NodeKind::Number => "number",
            NodeKind::Payee => "payee",
            NodeKind::Plus => "plus",
            NodeKind::Slash => "slash",
            NodeKind::String => "string",
            NodeKind::Tag => "tag",
            NodeKind::Unknown => "<unknown>",
        }
    }
}
