// @generated by scripts/generate_token_kind.py; do not edit.
// To regenerate, run: python scripts/generate_token_kind.py

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    Account,
    Asterisk,
    At,
    Atat,
    Bool,
    Comment,
    Currency,
    Date,
    Flag,
    Item,
    Key,
    Link,
    Minus,
    Narration,
    Number,
    Payee,
    Plus,
    Slash,
    String,
    Tag,
    Unknown,
}

impl TokenKind {
    pub fn from_name(name: &str) -> Option<Self> {
        Some(match name {
            "account" => TokenKind::Account,
            "asterisk" => TokenKind::Asterisk,
            "at" => TokenKind::At,
            "atat" => TokenKind::Atat,
            "bool" => TokenKind::Bool,
            "comment" => TokenKind::Comment,
            "currency" => TokenKind::Currency,
            "date" => TokenKind::Date,
            "flag" => TokenKind::Flag,
            "item" => TokenKind::Item,
            "key" => TokenKind::Key,
            "link" => TokenKind::Link,
            "minus" => TokenKind::Minus,
            "narration" => TokenKind::Narration,
            "number" => TokenKind::Number,
            "payee" => TokenKind::Payee,
            "plus" => TokenKind::Plus,
            "slash" => TokenKind::Slash,
            "string" => TokenKind::String,
            "tag" => TokenKind::Tag,
            _ => return None,
        })
    }

    pub fn name(&self) -> &'static str {
        match self {
            TokenKind::Account => "account",
            TokenKind::Asterisk => "asterisk",
            TokenKind::At => "at",
            TokenKind::Atat => "atat",
            TokenKind::Bool => "bool",
            TokenKind::Comment => "comment",
            TokenKind::Currency => "currency",
            TokenKind::Date => "date",
            TokenKind::Flag => "flag",
            TokenKind::Item => "item",
            TokenKind::Key => "key",
            TokenKind::Link => "link",
            TokenKind::Minus => "minus",
            TokenKind::Narration => "narration",
            TokenKind::Number => "number",
            TokenKind::Payee => "payee",
            TokenKind::Plus => "plus",
            TokenKind::Slash => "slash",
            TokenKind::String => "string",
            TokenKind::Tag => "tag",
            TokenKind::Unknown => "<unknown>",
        }
    }
}

