#!/usr/bin/env python3
"""Generate Rust NodeKind enum from node-types.json.

Usage:
    python scripts/generate_token_kind.py

workaround of https://github.com/tree-sitter/tree-sitter/issues/3276
"""

import json
import re
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__, "../..").resolve()
NODE_TYPES_PATH = ROOT / "src" / "node-types.json"
OUT_PATH = ROOT / "bindings" / "rust" / "node_kind.rs"


def to_pascal(name: str) -> str:
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", name) if p]
    if not parts:
        return "Unknown"
    ident = "".join(p[:1].upper() + p[1:] for p in parts)
    if ident[0].isdigit():
        ident = f"N{ident}"
    return ident


def is_terminal(node: Dict[str, Any]) -> bool:
    """Heuristically select terminal/named token kinds."""
    if not node.get("named", False):
        return False
    if node.get("subtypes"):
        return False
    if node.get("children"):
        return False
    fields = node.get("fields")
    if fields:
        # If there are any declared fields, treat it as non-terminal
        return False
    return True


def main() -> None:
    data = json.loads(NODE_TYPES_PATH.read_text(encoding="utf-8"))
    token_names = sorted({n["type"] for n in data if is_terminal(n)})

    variants = [to_pascal(name) for name in token_names]

    lines = [
        "// @generated by scripts/generate_token_kind.py; do not edit.",
        "// To regenerate, run: python scripts/generate_token_kind.py",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]",
        "pub enum NodeKind {",
    ]
    lines += [f"    {v}," for v in variants]
    lines.append("    Unknown,")
    lines.append("}")
    lines.append("")
    lines.append("impl From<&str> for NodeKind {")
    lines.append("    fn from(name: &str) -> Self {")
    lines.append("        match name {")
    lines += [
        f'            "{name}" => NodeKind::{variant},'
        for name, variant in zip(token_names, variants)
    ]
    lines.append("            _ => NodeKind::Unknown,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("impl NodeKind {")
    lines.append("    pub fn name(&self) -> &'static str {")
    lines.append("        match self {")
    lines += [
        f'            NodeKind::{variant} => "{name}",'
        for name, variant in zip(token_names, variants)
    ]
    lines.append('            NodeKind::Unknown => "<unknown>",')
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
